name=VIA_Arduino
version=0.1.0
author=Juarendra Ramadhani <jrjuarendra@gmail.com>
maintainer=Juarendra Ramadhani <jrjuarendra@gmail.com>
sentence=The ultimate Arduino implementation of the QMK VIA Custom Keyboard Protocol.
paragraph=The ultimate Arduino implementation of the QMK VIA Custom Keyboard Protocol. Includes major enterprise features and bug fixes.
category=Other
url=https://github.com/juarendra/VIA-Arduino
architectures=*
includes=VIA_Arduino.h
